const types = {
    RESET_STATE: "RESET_STATE",
    SET_ALERT: "SET_ALERT",
    SET_CHATS: "SET_CHATS",
    SET_OPENED_CHAT: "SET_OPENED_CHAT",
    UPDATE_CHATS: "UPDATE_CHATS",
    SET_IS_LOADING_MESSAGES: "SET_IS_LOADING_MESSAGES",
};

export default types;
