const types = {
    SET_CHATS: "SET_CHATS",
    SET_OPENED_CHAT: "SET_OPENED_CHAT",
    SET_IS_LOADING_MESSAGES: "SET_IS_LOADING_MESSAGES",
    UPDATE_CHAT_MESSAGES: "UPDATE_CHAT_MESSAGES",
    UPDATE_CHATS: "UPDATE_CHATS",
    SET_ALERT: "SET_ALERT",
};

export default types;
